language: android
jdk: oraclejdk7
env:
  global:
  - secure: glSM29zH6qcGWugWZt9cRDtgjq3/tPo+jLXmsFaYGQJjfZeAgtITvBS6u7yNmlYQCcJSMyW/QW7pwi7fTwoYssrOBpFXrvZWgnE1m+/ukoXiReUdXKOS9blRlOpKx2Ocpak0lgTS7oRo7JOgQ3oXtBny2UDHVDlHqFhPxZbOh7s=
  - secure: QM89U4SGeIiu7FYFoh6oLrn9TsKczQZhdLQu6fAoZIEpPvbgzP7tvLtNDd34esaIoj3V4/C4QL2u3Tnhd9mr+G36xtUWpurjA/dELRzTNra2UO8R3uc5C73omyNU2EOl/5ZOblzudtDqkRGDHf1hBNXaLys/PnL4Jaiv2ixLsrY=
android:
  components:
  - build-tools-20.0.0
  - android-19
  licences:
  - android-sdk-license-5be876d5
before_install:
- chmod +x gradlew
- openssl aes-256-cbc -k "$super_secret_password" -in ./video/secret_key.enc -out ./video/secret_key.gpg
  -d
- echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
after_success:
- ./gradlew :video:uploadArchives -PNEXUS_USERNAME="${NEXUS_USERNAME}" -PNEXUS_PASSWORD="${NEXUS_PASSWORD}"
  -Psigning.keyId="${SIGNING_KEY_ID}" -Psigning.password="${SIGNING_PASSWORD}" -Psigning.secretKeyRingFile="${SIGNING_KEY_RING_FILE}"
